export const ALBUMOK = [
  {
    eloado: "The Cure",
    album: "Disintegration",
    mufaj: "Gothic rock",
    megjelenes: 1989,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "The Cure",
    album: "Pornography",
    mufaj: "Gothic rock",
    megjelenes: 1982,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "The Cure",
    album: "Kiss Me, Kiss Me, Kiss Me",
    mufaj: "Gothic rock",
    megjelenes: 1987,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "The Cure",
    album: "Seventeen Seconds",
    mufaj: "Gothic rock",
    megjelenes: 1980,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "The Cure",
    album: "Three Imaginary Boys",
    mufaj: "Gothic rock",
    megjelenes: 1979,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "Joy Division",
    album: "Unknown Pleasures",
    mufaj: "Gothic rock",
    megjelenes: 1979,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "Joy Division",
    album: "Closer",
    mufaj: "Gothic rock",
    megjelenes: 1980,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "Queens of the Stone Age",
    album: "Queens of the Stone Age",
    mufaj: "Stoner rock",
    megjelenes: 1998,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "Queens of the Stone Age",
    album: "Rated R",
    mufaj: "Stoner rock",
    megjelenes: 2000,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "Queens of the Stone Age",
    album: "Songs for the Deaf",
    mufaj: "Stoner rock",
    megjelenes: 2002,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "Queens of the Stone Age",
    album: "Lullabies to Paralyze",
    mufaj: "Stoner rock",
    megjelenes: 2005,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "Queens of the Stone Age",
    album: "Era Vulgaris",
    mufaj: "Stoner rock",
    megjelenes: 2007,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "Queens of the Stone Age",
    album: "...Like Clockwork",
    mufaj: "Stoner rock",
    megjelenes: 2013,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "Fugazi",
    album: "Repeater",
    mufaj: "Post-hardcore",
    megjelenes: 1990,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "Fugazi",
    album: "13 Songs",
    mufaj: "Post-hardcore",
    megjelenes: 1989,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "Fugazi",
    album: "Red Medicine",
    mufaj: "Post-hardcore",
    megjelenes: 1995,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "Minor Threat",
    album: "First Two Seven Inches",
    mufaj: "Hardcore punk",
    megjelenes: 1981,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "Minor Threat",
    album: "Out of Step",
    mufaj: "Hardcore punk",
    megjelenes: 1983,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "Minor Threat",
    album: "Salad Days",
    mufaj: "Hardcore punk",
    megjelenes: 1985,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "Nine Inch Nails",
    album: "Broken - EP",
    mufaj: "Industrial rock",
    megjelenes: 1992,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "Nine Inch Nails",
    album: "The Downward Spiral",
    mufaj: "Industrial rock",
    megjelenes: 1994,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "Nine Inch Nails",
    album: "The Fragile",
    mufaj: "Industrial rock",
    megjelenes: 1999,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "Nine Inch Nails",
    album: "With Teeth",
    mufaj: "Industrial rock",
    megjelenes: 2005,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "Nine Inch Nails",
    album: "Year Zero",
    mufaj: "Industrial rock",
    megjelenes: 2007,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "Nine Inch Nails",
    album: "Ghosts I-IV",
    mufaj: "Industrial rock",
    megjelenes: 2008,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "Nine Inch Nails",
    album: "The Slip",
    mufaj: "Industrial rock",
    megjelenes: 2008,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "Nine Inch Nails",
    album: "Hesitation Marks",
    mufaj: "Industrial rock",
    megjelenes: 2013,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "Nine Inch Nails",
    album: "Not the Actual Events - EP",
    mufaj: "Industrial rock",
    megjelenes: 2016,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "Nine Inch Nails",
    album: "Add Violence - EP",
    mufaj: "Industrial rock",
    megjelenes: 2017,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "Nine Inch Nails",
    album: "Bad Witch",
    mufaj: "Industrial rock",
    megjelenes: 2018,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "Nine Inch Nails",
    album: "Ghosts V: Together",
    mufaj: "Industrial rock",
    megjelenes: 2020,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "Nine Inch Nails",
    album: "Ghosts VI: Locusts",
    mufaj: "Industrial rock",
    megjelenes: 2020,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "Sonic Youth",
    album: "Daydream Nation",
    mufaj: "Alternative rock",
    megjelenes: 1988,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "Sonic Youth",
    album: "Goo",
    mufaj: "Alternative rock",
    megjelenes: 1990,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "Sonic Youth",
    album: "Dirty",
    mufaj: "Noise rock",
    megjelenes: 1992,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "Sonic Youth",
    album: "Rather Ripped",
    mufaj: "Alternative rock",
    megjelenes: 2006,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "Radiohead",
    album: "Pablo Honey",
    mufaj: "Alternative rock",
    megjelenes: 1993,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "Radiohead",
    album: "The Bends",
    mufaj: "Alternative rock",
    megjelenes: 1995,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "Radiohead",
    album: "OK Computer",
    mufaj: "Alternative rock",
    megjelenes: 1997,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "Radiohead",
    album: "Kid A",
    mufaj: "Alternative rock",
    megjelenes: 2000,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "Radiohead",
    album: "Amnesiac",
    mufaj: "Alternative rock",
    megjelenes: 2001,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "Radiohead",
    album: "Hail to the Thief",
    mufaj: "Alternative rock",
    megjelenes: 2003,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "Radiohead",
    album: "In Rainbows",
    mufaj: "Alternative rock",
    megjelenes: 2007,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "Radiohead",
    album: "The King of Limbs",
    mufaj: "Alternative rock",
    megjelenes: 2011,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "Radiohead",
    album: "A Moon Shaped Pool",
    mufaj: "Alternative rock",
    megjelenes: 2016,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "Depeche Mode",
    album: "Black Celebration",
    mufaj: "Synthpop",
    megjelenes: 1986,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "Depeche Mode",
    album: "Music for the Masses",
    mufaj: "Synthpop",
    megjelenes: 1987,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "Depeche Mode",
    album: "Violator",
    mufaj: "Synthpop",
    megjelenes: 1990,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "Depeche Mode",
    album: "Songs of Faith and Devotion",
    mufaj: "Synthpop",
    megjelenes: 1993,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
  {
    eloado: "Depeche Mode",
    album: "Ultra",
    mufaj: "Synthpop",
    megjelenes: 1997,
    boritokep: "",
    dalok: [{}],
    keszlet: 0,
    ar: 0,
	leiras: ""
  },
];

export const FELHASZNALOK = [
  { felhasznalonev: "admin", jelszo: "admin" },
  { felhasznalonev: "felhasznalo", jelszo: "password" },
];
